package esw.template.http.server.cli

import java.io.ByteArrayOutputStream

import esw.template.http.server.BaseTestSuite

class ArgsParserTest extends BaseTestSuite {

  //Capture output/error generated by the parser, for cleaner test output. If interested, errCapture.toString will return capture errors.
  val outCapture = new ByteArrayOutputStream
  val errCapture = new ByteArrayOutputStream
  val parser     = new ArgsParser("esw-gateway-server")

  def silentParse(args: Array[String]): Option[Options] =
    Console.withOut(outCapture) {
      Console.withErr(errCapture) {
        parser.parse(args)
      }
    }

  "ArgsParser" must {
    "parse without arguments | ESW-86" in {
      val args = Array("")
      silentParse(args) shouldBe None
    }

    "parse when only port argument provided | ESW-86" in {
      val args = Array("--port", "8080")
      silentParse(args) shouldBe Some(Options(Some(8080)))
    }
  }
}
