#!/usr/bin/env bash -e
echo "Executing fake esw-ocs-app"
prefix="$3.$5"

curl -sS -X POST \
  http://localhost:7654/post-endpoint \
  -H 'Accept: */*' \
  -H 'Content-Type: application/json' \
  -d "{\"Register\":{\"AkkaRegistration\":{\"connection\":{\"prefix\":\"${prefix}\",\"componentType\":\"sequence_component\",\"connectionType\":\"akka\"},\"actorRefURI\":\"akka://agent-app@10.131.124.163:61380/user/agent-actor#1379701792\"}}}"