{
 "title": "Gateway",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Http Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Http Requests Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 1 },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "HTTP Requests /sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (msg) (rate(http_requests_total[1m]))",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "Commands passing through gateway/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (command_msg) (rate(http_requests_total{command_msg!=\"\"}[1m]))",
     "legendFormat": "{{command_msg}}"
    }
   ]
  },
  { "title": "Websocket Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Active WS connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum(websocket_active_request_total)"
    }
   ]
  },
  {
   "title": "Active Pattern Subscribers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "sum(websocket_active_request_total{msg=\"SubscribeWithPattern\"})"
    }
   ]
  },
  {
   "title": "Active Subscribers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum(websocket_active_request_total{msg=\"Subscribe\"})"
    }
   ]
  },
  {
   "title": "Active websocket requests /sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(websocket_active_request_total)",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "Event rate per client /sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app_name, username) (rate(websocket_messages_per_connection_total{msg=\"Subscribe\"}[1m]))"
    }
   ]
  },
  {
   "title": "Websocket active connections per client",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (app_name, username) (websocket_active_request_total)",
     "legendFormat": "{{app_name}} ({{username}})"
    }
   ]
  },
  {
   "title": "Active Subscriptions per client",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (app_name, username) (websocket_active_request_total{msg=\"Subscribe\"})",
     "legendFormat": "{{app_name}} ({{username}})"
    }
   ]
  },
  {
   "title": "Active Pattern Subscriptions per client",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (app_name, username, subscribed_pattern, subsystem) (websocket_active_request_total{msg=\"SubscribeWithPattern\"})",
     "legendFormat": "{{app_name}} ({{username}}) [Pattern:\"{{subscribed_pattern}}\", Subsystem:{{subsystem}}]"
    }
   ]
  }
 ]
}