package esw.template.http.server.cli

import java.io.ByteArrayOutputStream

import esw.template.http.server.BaseTestSuit

class ArgsParserTest extends BaseTestSuit {

  //Capture output/error generated by the parser, for cleaner test output. If interested, errCapture.toString will return capture errors.
  val outCapture = new ByteArrayOutputStream
  val errCapture = new ByteArrayOutputStream
  val parser     = new ArgsParser("esw-gateway-server")

  def silentParse(args: Array[String]): Option[Options] =
    Console.withOut(outCapture) {
      Console.withErr(errCapture) {
        parser.parse(args)
      }
    }

  test("ESW-86 | parse without arguments") {
    val args = Array("")
    silentParse(args) shouldBe None
  }

  test("ESW-86 | parse when only port argument provided") {
    val args = Array("--port", "8080")
    silentParse(args) shouldBe Some(Options(Some(8080)))
  }
}
