#### To Add version config. this API call will also mark it as active version
POST http://<your-ip>:4000/config/tmt/osw/version.conf
Content-Type: application/octet-stream

{
  scripts.version="0.1.0-SNAPSHOT"
}

##### To check active config
GET http://<your-ip>:4000/active-config/tmt/osw/version.conf



################################# Optional Steps ###################################################
#### To update version config
PUT http://<your-ip>:4000/config/tmt/osw/version.conf
Content-Type: application/octet-stream

{
  scripts.version="0.1.0-SNAPSHOT"
}

##### To make it active version of the config. id is returned from first/second call
PUT http://<your-ip>:4000/active-version/tmt/osw/version.conf?id=[id]&comment=abcd


##### To check if config is updated and marked as active
GET http://<your-ip>:4000/active-config/tmt/osw/version.conf
