
####Generate and save token (BearerToken.fromServer in LocationAuthTestWithKeycloak )
POST http://your_mc_ip:8081/auth/realms/TMT/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=tmt-frontend-app&grant_type=password&username=config-admin1&password=config-admin1


> {% client.global.set("access_token", response.body.access_token); %}

####

### Register component
POST http://localhost:7654/post-endpoint
Content-Type: application/json

{
  "_type" : "Register",
  "registration" : {
    "_type" : "HttpRegistration",
    "connection" : {
      "prefix" : "IRIS.filter.wheel",
      "componentType" : "HCD",
      "connectionType" : "http"
    },
    "port" : 8080,
    "path" : "path1",
    "networkType" : {
      "_type" : "Inside"
    },
    "metadata" : { }
  }
}

###

### validate
POST http://your_mc_ip:8090/post-endpoint
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "_type": "ComponentCommand",
  "componentId": {
    "prefix": "IRIS.filter.wheel",
    "componentType": "hcd"
  },
  "command": {
    "_type": "Validate",
    "controlCommand": {
      "_type": "Observe",
      "source": "CSW.ncc.trombone",
      "commandName": "startExposure",
      "maybeObsId":"2020A-001-123",
      "paramSet": []
    }
  }
}

### submit
POST http://localhost:8090/post-endpoint
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "_type": "ComponentCommand",
  "componentId": {
    "prefix": "IRIS.trombonehcd",
    "componentType": "hcd"
  },
  "command": {
    "_type": "Submit",
    "controlCommand": {
      "_type": "Setup",
      "source": "CSW.ncc.trombone",
      "commandName": "startExposure",
      "maybeObsId": [
        "2020A-001-123"
      ],
      "paramSet": []
    }
  }
}

#### curl -H "Origin: http://localhost:3000" -H "Content-Type: application/json" -d '{"_type": "ListEntries"}' --include  -X POST http://localhost:7654/post-endpoint
GET http://localhost:9003/api
Origin: http://localhost:3000
Content-Type: application/json


###
