### submit
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "ComponentCommand": {
    "componentId": {
      "prefix": "esw.test",
      "componentType": "assembly"
    },
    "command": {
      "Submit": {
        "Setup": {
          "source": "esw.test",
          "commandName": "c1",
          "maybeObsId": [
            "obsId"
          ],
          "paramSet": []
        }
      }
    }
  }
}

### validate
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "ComponentCommand": {
    "componentId": {
      "name": "test",
      "componentType": "assembly"
    },
    "command": {
      "Validate": {
        "Setup": {
          "source": "esw.test",
          "commandName": "c1",
          "maybeObsId": [
            "obsId"
          ],
          "paramSet": []
        }
      }
    }
  }
}

### oneway
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "ComponentCommand": {
    "componentId": {
      "name": "test",
      "componentType": "assembly"
    },
    "command": {
      "Oneway": {
        "Setup": {
          "source": "esw.test",
          "commandName": "c1",
          "maybeObsId": [
            "obsId"
          ],
          "paramSet": []
        }
      }
    }
  }
}

### publish
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "PublishEvent": {
    "event": {
      "ObserveEvent": {
        "eventId": "7a4cd6ab-6077-476d-a035-6f83be1de42c",
        "source": "wfos.blue.filter",
        "eventName": "filter_wheel",
        "eventTime": "2017-08-09T06:40:00.898Z",
        "paramSet": [
          {
            "StructKey": {
              "keyName": "myStruct",
              "values": [
                {
                  "paramSet": [
                    {
                      "StringKey": {
                        "keyName": "ra",
                        "values": [
                          "12:13:14.1"
                        ],
                        "units": "NoUnits"
                      }
                    },
                    {
                      "StringKey": {
                        "keyName": "dec",
                        "values": [
                          "32:33:34.4"
                        ],
                        "units": "NoUnits"
                      }
                    },
                    {
                      "DoubleKey": {
                        "keyName": "epoch",
                        "values": [
                          1950
                        ],
                        "units": "NoUnits"
                      }
                    }
                  ]
                }
              ],
              "units": "NoUnits"
            }
          }
        ]
      }
    }
  }
}

### get
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "GetEvent": {
    "eventKeys": [
      {
        "source": "wfos.blue.filter",
        "eventName": "filter_wheel"
      }
    ]
  }
}

### setSeverity
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "SetAlarmSeverity": {
    "alarmKey": {
      "prefix": "NFIRAOS.SampleHcd",
      "name": "counterTooHighAlarm"
    },
    "severity": "Major"
  }
}

###
