############### Command Service #############
### validate
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "_type": "ComponentCommand",
  "componentId": {
    "prefix": "CSW.ncc.trombone",
    "componentType": "hcd"
  },
  "command": {
    "_type": "Validate",
    "controlCommand": {
      "_type": "Observe",
      "source": "CSW.ncc.trombone",
      "commandName": "move",
      "maybeObsId": [
        "obs001"
      ],
      "paramSet": []
    }
  }
}

### submit immediate
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "_type": "ComponentCommand",
  "componentId": {
    "prefix": "CSW.ncc.trombone",
    "componentType": "hcd"
  },
  "command": {
    "_type": "Submit",
    "controlCommand": {
      "_type": "Observe",
      "source": "CSW.ncc.trombone",
      "commandName": "immediate",
      "maybeObsId": [
        "obs001"
      ],
      "paramSet": []
    }
  }
}

### submit
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "_type": "ComponentCommand",
  "componentId": {
    "prefix": "CSW.ncc.trombone",
    "componentType": "hcd"
  },
  "command": {
    "_type": "Submit",
    "controlCommand": {
      "_type": "Observe",
      "source": "CSW.ncc.trombone",
      "commandName": "long",
      "maybeObsId": [
        "obs001"
      ],
      "paramSet": []
    }
  }
}

### oneway
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "_type": "ComponentCommand",
  "componentId": {
    "prefix": "CSW.ncc.trombone",
    "componentType": "hcd"
  },
  "command": {
    "_type": "Oneway",
    "controlCommand": {
      "_type": "Observe",
      "source": "CSW.ncc.trombone",
      "commandName": "temp",
      "maybeObsId": [
        "obs001"
      ],
      "paramSet": []
    }
  }
}

### oneway
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "_type": "ComponentCommand",
  "componentId": {
    "prefix": "CSW.ncc.trombone",
    "componentType": "hcd"
  },
  "command": {
    "_type": "Query",
    "runId": "e4641028-a048-46f4-bb40-69bc89a699e0"
  }
}

############### Event Service #############
### publish
POST http://localhost:8090/post-endpoint
Content-Type: application/json
X-Real-IP: 10.131.20.154

{
  "_type": "PublishEvent",
  "event": {
    "_type": "ObserveEvent",
    "eventId": "1a745d6b-30b6-4503-a09e-e3bdbb680795",
    "source": "CSW.ncc.trombone",
    "eventName": "offline",
    "eventTime": "2020-02-18T05:57:09.754352Z",
    "paramSet": []
  }
}

### get
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "_type": "GetEvent",
  "eventKeys": [
    {
      "source": "CSW.ncc.trombone",
      "eventName": "offline"
    }
  ]
}

############### Alarm Service #############
### setSeverity
POST http://localhost:8090/post-endpoint
Content-Type: application/json

{
  "_type": "SetAlarmSeverity",
  "alarmKey": {
    "prefix": "CSW.ncc.trombone",
    "name": "someAlarm"
  },
  "severity": "okay"
}

###
