### queryFinal
GET http://localhost:8090/websocket-endpoint
Content-Type: application/json

{"QueryFinal": {"componentId": {"name": "SampleHcd", "componentType": "HCD"}, "runId": "test-runId"}}

### subscribeCurrentState
GET http://localhost:8090/websocket-endpoint
Content-Type: application/json

{"SubscribeCurrentState": {"componentId": {"name": "SampleHcd", "componentType": "HCD"}, "stateNames": [{"name": "stateName1"}], "maxFrequency": [2]}}

### subscribe
GET http://localhost:8090/websocket-endpoint
Content-Type: application/json

{"Subscribe": {"eventKeys": [{"source": "wfos.blue.filter", "eventName": "filter_wheel"}], "maxFrequency": [2]}}
